runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  SQLALCHEMY_DATABASE_URI: 'sqlite:///test.db'
  JWT_SECRET_KEY: 'your_jwt_secret_key'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
